apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app: {{ .Release.Name }}-nginx
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |-
    {{ .Files.Get "configmap/nginx.conf" | nindent 4 }}
  # nginx.conf: |
  #   server {
  #     listen 8080;
  #     location /api/v1/movies {
  #       proxy_pass http://movie-service:8000/api/v1/movies;
  #     }

  #     location /api/v1/casts {
  #       proxy_pass http://cast-service:8000/api/v1/casts;
  #     }
  #   }