apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ .Release.Name }}-nginx
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.nginx.service.type }} #NodePort
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
  - name: {{ .Release.Name }}-nginx-port
    port: {{ .Values.nginx.service.port }} #8080
    targetPort: {{ .Values.nginx.service.port }} #8081
    # nodePort: {{ .Values.nginx.service.nodePort }} #30091