apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cast-db-secret
  labels:
    app: {{ .Release.Name }}-cast-db
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.cast_db.values.default_db }}
  POSTGRES_USER: {{ .Values.cast_db.values.default_user }}
  POSTGRES_PASSWORD: {{ .Values.cast_db.values.default_password }}
  POSTGRES_HOST_AUTH_METHOD: trust