apiVersion: v1
kind: Service
metadata:
  name: cast-db
  labels:
    app: {{ .Release.Name }}-cast-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.cast_db.service.port }}
  selector:
    app: {{ .Release.Name }}-cast-db