apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels:
    app: {{ .Release.Name }}-cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-cast-service
  ports:
  - name: {{ .Release.Name }}-cast-service-port
    port: {{ .Values.cast_service.service.port }} #8000
    targetPort: {{ .Values.cast_service.service.port }} #8002
    # nodePort: {{ .Values.cast_service.service.nodePort }} #30091