apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-movie-db-volume
  labels:
    app: {{ .Release.Name }}-movie-db
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.movie_db.storage.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/db