apiVersion: v1
kind: Service
metadata:
  name: movie-db
  labels:
    app: {{ .Release.Name }}-movie-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.movie_db.service.port }}
  selector:
    app: {{ .Release.Name }}-movie-db