# namespace: helm

nginx:
  image:
    repository: nginx
    tag: latest
  service:
    port: 8080
    targetPort: 8081
    type: NodePort

movie_service:
  image:
    repository: benjaminfiche77/jenkins-exam
    tag: latest-movie
  service:
    port: 8000
    targetPort: 8001
    # type: ClusterIP
  values:
    db_url: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
    cast_url: http://cast-service:8000/api/v1/casts/

cast_service:
  image:
    repository: benjaminfiche77/jenkins-exam
    tag: latest-cast
  service:
    port: 8000
    targetPort: 8002
    # type: ClusterIP
  values:
    db_url: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev

movie_db:
  image:
    repository: postgres
    tag: 12.1-alpine
  service:
    port: 5432
  storage:
    size: 10Gi
  values:
    default_user: movie_db_username
    default_password: movie_db_password
    default_db: movie_db_dev

cast_db:
  image:
    repository: postgres
    tag: 12.1-alpine
  service:
    port: 5432
  storage:
    size: 10Gi
  values:
    default_user: cast_db_username
    default_password: cast_db_password
    default_db: cast_db_dev