apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service
  labels:
    app: {{ .Release.Name }}-movie-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-service
    spec:
      containers:
        - name: {{ .Release.Name }}-movie-service
          image: "{{ .Values.movie_service.image.repository }}:{{ .Values.movie_service.image.tag }}" #benjaminfiche77/kubexamapp:latest
          imagePullPolicy: Always
          env:
          - name: DATABASE_URI
            value: {{ .Values.movie_service.values.db_url }}
          ports:
          - containerPort: {{ .Values.movie_service.service.port }} #8000